FROM mongo-express:latest

MAINTAINER Seth Terry

ENV ME_CONFIG_OPTIONS_EDITORTHEME="ambiance" 
ENV ME_CONFIG_BASICAUTH_USERNAME="thats" 
ENV ME_CONFIG_BASICAUTH_PASSWORD="right" 
ENV ME_CONFIG_MONGODB_SERVER="mongodb"